config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  #devise_for :admins
  resources :friends
  #get 'home/index'
  get 'home/about'
  get 'home/contact'
  #root 'home#index'
  #root 'friends#index'
  get 'admin/login'
  root 'admin/dashboard#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    if user_signed_in?
    @friends = current_user.friends
  else
    @friends = Friend.all
  end
  render json: {code: 200, status: true, message: 'Updated successfully', data: {friends: @friends}}
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
   # @friend = Friend.new
    @friend= current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend= current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end
   def correct_user
    @friend=current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Access Denied!" if @friend.nil?
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :instagram, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br/>
  <div>
    
    <%= form.text_field :first_name , class: "form-control",placeholder: "First Name"%>
  
  </div>

<br/>
  <div>
   
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name"%>
  </div>
<br/>
  <div>
  
    <%= form.text_field :email, class: "form-control", placeholder: "Email: name@example.com" %>
  </div>
<br/>
  <div>
    
    <%= form.text_field :phone, class: "form-control", placeholder: "Phone" %>
  </div>
<br/>

    <div>
    <%= form.text_field :instagram, class: "form-control", placeholder: "IG: @username"%>
  </div>
  <div>
    <%= form.number_field :user_id, class: "form-control",id: :friends_user_id, value: current_user.id, type: :hidden%>
  </div>

<br/>
  <div class = "actions">
    <%= form.submit class: 'btn btn-secondary'%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>

    <div class="jumbotron">
  <h1 class="display-4"><%= friend.first_name %> <%= friend.last_name %></h1>
  <p class="lead">BCA III YR STUDENT</p>
  <hr class="my-4">
  <p><%= friend.email %> | <%= friend.phone %> | <%= friend.instagram %></p>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-secondary" %>
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary btn-dark" %>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class: "btn btn-info"%> |
  <%= link_to "Back to friends", friends_path, class: "btn btn-primary"%>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
<div class= "container">
<h1>Friends List</h1>
<br>
</div>

<table class="table table-striped table-bordered table-hover">
<thead class= "thead-dark">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Instagram</th>
    <th>User ID</th>
    <th> </th>
  </tr>
</thead>

<tbody>

  <% @friends.each do |friend| %>
    <tr>
    <td><%=link_to "#{friend.first_name} #{friend.last_name}",friend %> 
    </td>
    <td><%= friend.email %></td>
    <td><%= friend.phone %></td>
    <td><%= friend.instagram %></td>
    <td><%= friend.user_id%></td>
   
    
    <td><%= button_to 'Delete', friend, class: "btn btn-outline-danger btn-sm", method: :delete, form: {data: {turbo_confirm: "Are you sure? " + friend.first_name + " will be deleted from your friends list!"}}%></td>
  </tr>
  <% end %>
</tbody>
</table>
    <br>
<%= link_to "New friend", new_friend_path, class: "btn btn-secondary" %>

<% else %>
  <h1>Hello World! </h1>
This is my first Rails Webpage...</br></br>
<%= link_to "Explore Now", new_user_registration_path, class: "btn btn-info" %>
<%= link_to "Welcome Back", new_user_session_path, class: "btn btn-secondary" %>
<% end %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>


<%= render "form", friend: @friend %>

<br/>

<div>
  <%= link_to "Back to friends", friends_path, class: "btn btn-info" %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
  
  <div>
  <%= button_to "Destroy this friend", @friend, class: "btn btn-danger", method: :delete, form: { data: {turbo_confirm: "Are you sure? " + @friend.first_name + " will be deleted from your friends list!"} }%>
</div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<%= link_to 'Friends App', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
      	<%= link_to "About Us", home_about_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
      	<%= link_to "Friends", friends_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
      	<%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
      </li>

      
          <li class="nav-item">
      	     <%= button_to "Sign Out",  destroy_user_session_path,class: "text-white text-muted btn btn-dark", method: :delete, form: {data: {turbo_confirm: "Are you sure? You will be logged out!"}} %>
          </li>
          <li class="nav-item">
      	      <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
           <% else %>
          <li class="nav-item">
      	      <%= link_to "Sign Up",  new_user_registration_path, class:"nav-link" %>
         </li>
          <li class="nav-item">
      	      <%= link_to "Sign In",  new_user_session_path, class:"nav-link" %>
         </li>
         <% end %>
            <li class="nav-item">
      	<%= link_to "Contact Us", home_contact_path, class:"nav-link" %>
      </li>
      
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About us...</h1>

app/views/home/contact.html.erb
<h1>Thanks for visiting Customer Support</h1>
<h2>Chat with our CSM: <br/> Whatsapp Number: +91 7068796751</h2>

app/views/home/index.html.erb
<h1>Hello World! </h1>
This is my first Rails Webpage...

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Friends App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
    <% if notice %>
        <%= render 'layouts/alerts' %>
        <% end %>
      <br/>
    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>